import Head from "next/head";
import Image from "next/image";
import logo from "../../public/logo.svg";
import Item from "../components/item";
import interactive from "../../public/desktop/image-interactive.jpg";
import { useState } from "react";

import deep_desktop from "../../public/desktop/image-deep-earth.jpg";
import deep_mobile from "../../public/mobile/image-deep-earth.jpg";

import curiosity from "../../public/desktop/image-curiosity.jpg";
import curiosity_mobile from "../../public/mobile/image-curiosity.jpg";

import fisheye from "../../public/desktop/image-fisheye.jpg";
import fisheye_mobile from "../../public/mobile/image-fisheye.jpg";

import from_above from "../../public/desktop/image-from-above.jpg";
import from_above_mobile from "../../public/mobile/image-from-above.jpg";

import grid from "../../public/desktop/image-grid.jpg";
import grid_mobile from "../../public/mobile/image-grid.jpg";

import night_arcade from "../../public/desktop/image-night-arcade.jpg";
import night_arcade_mobile from "../../public/mobile/image-night-arcade.jpg";

import pocket_borealis from "../../public/desktop/image-pocket-borealis.jpg";
import pocket_borealis_mobile from "../../public/mobile/image-pocket-borealis.jpg";

import soccer_team from "../../public/desktop/image-soccer-team.jpg";
import soccer_team_mobile from "../../public/mobile/image-soccer-team.jpg";

import facebook from "../../public/icon-facebook.svg";
import twitter from "../../public/icon-twitter.svg";
import instagram from "../../public/icon-instagram.svg";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  const handleClick = () => {
    setIsOpen(!isOpen);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <section id="hero">
        <div className="container relative max-w-6xl mx-auto px-6 py-12">
          <nav className="flex item-center justify-between font-bold text-white">
            <Image src={logo} />
            <div className="hidden h-10 md:flex md:space-x-8">
              <div className="group">
                <a href="#">About</a>
                <div className="mx-2 group-hover:border-b group-hover:border-blue-100"></div>
              </div>
              <div className="group">
                <a href="#">Discover more</a>
                <div className="mx-2 group-hover:border-b group-hover:border-blue-100"></div>
              </div>
              <div className="group">
                <a href="#">Contacts</a>
                <div className="mx-2 group-hover:border-b group-hover:border-blue-100"></div>
              </div>
            </div>
            {/* hamburger */}
            <div className="md:hidden">
              <button
                onClick={handleClick}
                id="burger"
                type="button"
                className={
                  isOpen
                    ? "open z-40 block hamburger md:hidden focus:outline-none"
                    : "z-40 block hamburger md:hidden focus:outline-none"
                }
              >
                <span className="hamburger-top"></span>
                <span className="hamburger-mid"></span>
                <span className="hamburger-bot"></span>
              </button>
            </div>
          </nav>
          <div id="menu" className={isOpen ? "responsive" : "hidden"}>
            <a href="#" className="hover:text-pink-500">
              About
            </a>
            <a href="#" className="hover:text-pink-500">
              Something Else
            </a>
            <a href="#" className="hover:text-pink-500">
              Contancts
            </a>
          </div>
          {/* mobile menu */}
          <div className="max-w-lg mt-32 mb-32 p-4 font-sans text-4xl text-white uppercase border-2 md:p-10 md:m-32 md:mx-0 md:text-6xl">
            Impressive experience that deliver
          </div>
        </div>
      </section>
      <section id="features">
        <div className="relative container flex flex-col max-w-6xl mx-auto my-32 px-6 text-slate-800 md:flex-row cd:px-0 ">
          <Image src={interactive} alt="image-interactive" />
          <div className="top-48 pr-0 bg-white md:absolute md:right-0 md:py-20 md:pl-20">
            <h2 className="max-w-lg mt-10 mb-6 font-sans text-4xl text-center text-slate-900 uppercase md:text-5xl md:mt-0 md:text-left">
              The leader in interactive VR
            </h2>
            <p className="max-w-md text-center md:text-left">
              lorem ipsum something lorem ipsum something lorem ipsum something
              lorem ipsum something lorem ipsum something lorem ipsum something
              lorem ipsum something lorem ipsum something
            </p>
          </div>
        </div>
      </section>
      <section id="creations">
        <div className="container max-w-6xl mx-auto my-32 px-6 text-slate-900 md:px-0">
          <div className="flex justify-center md:justify-between mb-20">
            <h2 className="text-4xl text-center uppercase md:text-left md:text-5xl">
              our creations
            </h2>
            <button className="btn hidden md:block">See all</button>
          </div>
          <div className="item-container">
            <Item img={deep_desktop} img_mob={deep_mobile} text="Deep Earth" />
            <Item img={curiosity} img_mob={curiosity_mobile} text="Curiosity" />
            <Item img={fisheye} img_mob={fisheye_mobile} text="Fisheye" />
            <Item
              img={from_above}
              img_mob={from_above_mobile}
              text="From Above"
            />
          </div>
          <div className="item-container mt-8">
            <Item img={grid} img_mob={grid_mobile} text="Grid" />
            <Item
              img={pocket_borealis}
              img_mob={pocket_borealis_mobile}
              text="Pocket Borealis"
            />
            <Item
              img={soccer_team}
              img_mob={soccer_team_mobile}
              text="Soccer Team"
            />
            <Item
              img={night_arcade}
              img_mob={night_arcade_mobile}
              text="Night Arcade"
            />
          </div>
          <div className="flex justify-center mt-10 md:hidden">
            <button className="btn w-full md:hidden">See all</button>
          </div>
        </div>
      </section>
      <section id="footer" className="bg-slate-900">
        <div className="container max-w-6xl py-10 mx-auto">
          <div className="flex flex-col items-center mb-8 space-y-6 md:flex-row md:space-y-0 md:justify-between md:items-start">
            <div className="flex flex-col items-center justify-space-between md:items-start md:space-y-4">
              <div className="h-8 mb-4">
                <Image src={logo} className="w-44 md:ml-3" />
              </div>
              <div className="flex flex-col items-center space-y-4 font-bold text-white md:flex-row md:space-y-0 md:space-x-6 md:ml-3">
                <div className="h-10 group">
                  <a href="#">About</a>
                  <div className="mx-2 group-hover:border-b group-hover:border-blue-800"></div>
                </div>
                <div className="h-10 group">
                  <a href="#">Something Else</a>
                  <div className="mx-2 group-hover:border-b group-hover:border-blue-800"></div>
                </div>
                <div className="h-10 group">
                  <a href="#">Contacts</a>
                  <div className="mx-2 group-hover:border-b group-hover:border-blue-800"></div>
                </div>
              </div>
            </div>
            <div className="flex flex-col items-center justify-between space-y-4 mx-auto md:mx-0 text-slate-500">
              <div className="flex items-center justify-center space-x-4 md:justify-end">
                <div className="h-8 group">
                  <a href="#">
                    <Image src={facebook} className="h-6" />
                  </a>
                </div>
                <div className="h-8 group">
                  <a href="#">
                    <Image src={twitter} className="h-6" />
                  </a>
                </div>
                <div className="h-8 group">
                  <a href="#">
                    <Image src={instagram} className="h-6" />
                  </a>
                </div>
              </div>
              <div className="font-bold">&copy;2023 loopstudios</div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
